name: Push Notification

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          from: ${{ secrets.MAIL_FROM }} # mail gönderdiğinizde ne görünsün örneğin: "GitHub Action"
          to: ${{ secrets.MAIL_TO }}     # push işlemi olduğunda bu mail kime gitsin
          username: ${{ secrets.MAIL_USERNAME }} # mail gönderme işlemi için kullanacağınız mail adresi, mail nereden atılacak
          password: ${{ secrets.MAIL_PASSWORD }} # o mail adresinin şifresi
          subject: "Push Notification" # mail konusu
          body: "Push Notification" # mail içeriği
